### ISSUE TITLE
Objects are not updating

### ISSUE THREAD

**Issue by sharkaev** [gabrielmbmb/vuex-multi-tab-state#16]
First of all, thank you very much for your project! It saved me a lot of time!

I found a bug with keys deletion in a Vuex state object

it is similar to the closed issue with Array update

i've tried to delete key in object this way:

`
DELETE_KEY(state, key){
    del state.obj[key]
}
`

and obviously that didn't work because of the Vue reactivity. Then i've tried:
`
DELETE_KEY(state, key){
    Vue.delete(state.obj, key)
}
`

and that also didn't work. Lastly i've tried to delete object key with it's replacement of a new object. Also didn't work

**Comment by gabrielmbmb** [comment]
Hi! Thank you for reporting the issue. I will try to test this and find a solution as fast as possible.

**Comment by amandiobm** [comment]
Hey all, I still have issues with this.

My LocalStorage doesn't; get updated with the latest changes of the store.
