### ISSUE TITLE
Is GPL license intended?

### ISSUE THREAD

**Issue by jaredthirsk** [gabrielmbmb/vuex-multi-tab-state#2]
This looks exactly like what I need, but I was shocked to notice the license is GPL.  This is much more restrictive than the MIT license used by vuex-persistedstate, vuex, or vue.   It means there's no way in the world I can use this and I would have to implement something similar on my own, and I'm sure many others would be in the same boat.

So I'm wondering if this was an intentional choice.  If so, you can close this issue and have a nice day.  Otherwise, I would muchly appreciate changing the license to MIT (or similar) to match vuex-persistedstate.

**Comment by gabrielmbmb** [comment]
Yes, I suppose the GPL is very restrictive. I'll change it to MIT.

**Comment by gabrielmbmb** [comment]
I just uploaded version 1.0.10 which is already under the MIT license.

**Comment by jaredthirsk** [comment]
Thank you!
