### ISSUE TITLE
Vue 3 / Vuex 4 support?

### ISSUE THREAD

**Issue by ttntm** [gabrielmbmb/vuex-multi-tab-state#23]
Hi, I've been using this plugin in Vue 2 and tried using it with Vue 3 and Vuex 4 now.

When more than 1 tab are open, CPU usage increases dramatically and the browser gets crippled and unresponsive.

So, now the question is: should Vue 3 with Vuex 4 be supported already, or is this plugin simply not there yet (if so, do you plan on updating it)?

**Comment by gabrielmbmb** [comment]
Hi @ttntm. I haven't checked if Vuex has suffered any relevant change in Vue 3 or Vue 4 that breaks the plugin or makes it work badly. I will check it!

**Comment by ttntm** [comment]
Thanks! If it helps, I was using Brave Version 1.12.105 Chromium: 84.0.4147.105 (Official Build) on Manjaro Linux (64-bit) when I encountered this potential issue.

Once commented out, it all worked fine (except for multi tab state of course...). No idea what might be causing this, but it felt like some sort of endless loop or some other infinite operation was going on filling up the CPU and destroying the browser. 

No errors showed up in the Console btw. - I haven't had a look at it with a debugger, but I could do that if you can't find anything -- just let me know.

**Comment by gabrielmbmb** [comment]
Hey! I've been checking the plugin with Vue 3 and I couldn't detect any failure or any increment on the CPU workload. Could you provide me more info? Like the kind of state you are trying to keep synced (object, array, ...)

**Comment by ttntm** [comment]
Thanks for looking into it.

Here's my app's store: https://github.com/ttntm/watchlist/tree/master/src/store

It's module based and the action that I noticed problems with is called `attemptLogout` - you can have a look at it [here](https://github.com/ttntm/watchlist/blob/b5272a77ff4b77f0f8d9c4e11804af4e2076d6ba/src/store/modules/user.js#L129)

I'm using the same user authentication logic in a Vue 2 app together with your plugin and it works flawlessly.

I'll see if I can get any more info re: what's happening at runtime and I'll also test in some other browsers.

**Comment by gabrielmbmb** [comment]
Hey again! You have installed [vuex-persistedstate](https://github.com/robinvdvleuten/vuex-persistedstate) instead of vuex-multi-tab-state. Maybe you came to the wrong repository!

**Comment by gabrielmbmb** [comment]
I was suspicious of setting the value to _null_, but I checked it and that's not the problem

**Comment by ttntm** [comment]
Thanks for the responsiveness, I had your plugin uninstalled for production deployment some days ago, that's why it's not there.

I'm currently working with the Chromium's and Firefox's respective debuggers and I've already found (and fixed) the infinite loop. It was an `onBeforeUpdate` Vue 3 hook that was causing a sorting function to freak out - one tab sorted the array, the other one got the updated array from your plugin and sorted it again and so on.

I'm still struggling with some weird behaviour on logout, but I'm rather sure your plugin is _not_ the cause of it (or any issues for that matter) - it seems to do it's job well and I'm sorry for suggesting it didn't.

**Comment by gabrielmbmb** [comment]
No problem!
