### ISSUE TITLE
lodash is a heavy dependency

### ISSUE THREAD

**Issue by moltar** [gabrielmbmb/vuex-multi-tab-state#3]
Hi Gabriel,

First of all, great module! Love that it is in TypeScript.

Nice to have an alternative to `vuex-shared-mutations`.

---

I think `lodash` is a heavy dependency and the whole package would get bundled and shipped to the frontend.

If `lodash` functionality is really needed, then I think the project should use individual `lodash` modules.

You can install every lodash function separately via `lodash.${functionName}` package.

E.g. `merge` is available via https://www.npmjs.com/package/lodash.merge

**Comment by gabrielmbmb** [comment]
You're absolutely right. I will fix this ASAP.

**Comment by gabrielmbmb** [comment]
Hello @moltar,

I released v1.0.11 in npm with only the needed lodash methods. Thank you for your advice!
