### ISSUE TITLE
Add compression possibility to save localStorage space

### ISSUE THREAD

**Issue by j5k** [gabrielmbmb/vuex-multi-tab-state#31]
At the moment much space is lost because the object keys are often repeated. Maybe you can index all at the beginning and substitute it with numbers later. Or another solution. 5MB limit are too few :-(

Thanks for this awesome piece of code!

**Comment by gabrielmbmb** [comment]
Hey @j5k, could you clarify a little more? I don't understand what you mean when you say that object keys are often repeated.

**Comment by j5k** [comment]
This package works perfectly for my needs. But the only problem is, that the strict storage limit of 5MB for localStorage is very low. So I looked at your saved data and saw a normal JSON string. A quick example:
```
{
"id":"bxeww1tsn7cbani9dhu5rl",
"state":{
  "countries":{
    "AF":{"code":"AF","name":"Afghanistan","d_code":"+93","package_zone":"2"},
    "AL":{"code":"AL","name":"Albania","d_code":"+355","package_zone":"1"},
    "DZ":{"code":"DZ","name":"Algeria","d_code":"+213","package_zone":"2"},
    "AS":{"code":"AS","name":"American Samoa","d_code":"+1","package_zone":"2"},
    "AD":{"code":"AD","name":"Andorra","d_code":"+376","package_zone":"1"},
    ...
```

You see, the array keys are present multiple times and needs a lot of storage without more informational content.

One approach would be to index the array key. For example:
```
"id":"bxeww1tsn7cbani9dhu5rl",
"key_index":{"1":"code","2":"name","3":"d_code","4":"package_zone"},
"state":{
  "countries":{
    "AF":{"1":"AF","2":"Afghanistan","3":"+93","4":"2"},
    "AL":{"1":"AL","2":"Albania","3":"+355","4":"1"},
    "DZ":{"1":"DZ","2":"Algeria","3":"+213","4":"2"},
    "AS":{"1":"AS","2":"American Samoa","3":"+1","4":"2"},
    "AD":{"1":"AD","2":"Andorra","3":"+376","4":"1"},
    ...
```

I'm sure there are better approaches as well.

**Comment by d4g0** [comment]
I’m curious my friend, do you really need to have in sync that pile of data ? If is so big as i imagining,  why don’t  you leave that state for a real database ?

Sent with 💚 from havana

**Comment by gabrielmbmb** [comment]
As @d4g0 pointed out, I didn't see the need to store so much data in local storage. The package was initially made to sync small amount of data between two tabs, like login state or similar. @j5k your solution will reduce the size of the data that `vuex-multi-tab-state` uses in local storage, but I think that can be done without coding it on the plugin. You could index your state and `vuex-multi-tab-state` will only have to save that indexed state.
