### ISSUE TITLE
How to use with nuxt?

### ISSUE THREAD

**Issue by jonalxh** [gabrielmbmb/vuex-multi-tab-state#7]
Hi. I've tried to set it using Nuxt but it does not work, I've declared it as a `plugin` in my` store.js `and it does nothing, I've setted it in my `nuxt.config.js` in modules block but result is the same.

I think it is the better vuex persistance plugin, please help me adding it. Thanks.

**Comment by gabrielmbmb** [comment]
Hello, @jonalxh . I didn't tried to use this plugin with Nuxt.js before. I'll check this asap and I will try to provide you a solution.

**Comment by jonalxh** [comment]
Thank you so much. @gabrielmbmb 

I'll be waiting for you, because I've not been able to set it with any lpugin for store persistance.

**Comment by gabrielmbmb** [comment]
Hi again @jonalxh. I added instructions in [README.md](https://github.com/gabrielmbmb/vuex-multi-tab-state#nuxtjs). Also, I added a [NuxtJS project](https://github.com/gabrielmbmb/vuex-multi-tab-state/tree/master/examples/nuxt) example which integrates the plugin.

**Comment by jonalxh** [comment]
Wow. This is amazing,
I was trying to do it in a similar way but i had no idea of the client mode, I've tried and it worked instantly.
I am very grateful to you.
