### ISSUE TITLE
Two vue projects sharing the same state and missing states

### ISSUE THREAD

**Issue by scarstreet** [gabrielmbmb/vuex-multi-tab-state#77]
I made two vue projects. Project A needs this plugin's feature so I made project B to test this plugin. When project B proved to be working, I implemented the plugin on project A. But then I had an error when I tried to login in project A. It says that a state in project A is undefined and I tried to check by console logging the whole state of project A. What I found when console logging it was that the state from project B was in the state of project A even though project B was not running in my localhost. Also, there was a missing state from project A, the state that was missing looked like this :

```
  profile: {
    id: null,
    name: null,
    role: null,
    email: null,
    photoUrl: null,
    ownPatients: null,
    pastPatients: null,
  }
```

Does anyone know how to fix this or how to atleast get rid of Project B's data? Thanks.

**Comment by gabrielmbmb** [comment]
Hey! The plugin will save the data of your Vuex store in local storage using the domain. What that this means? I guess that you have executed project B in `localhost`, so project B data has been saved in the local storage of `localhost`. After that, you have executed project A and you have also served it under `localhost`, but the old data of B is still there.

Have you tried to remove the local storage data of `localhost`? If you're using Firefox you can right click the webpage, then _Inspect_, then click the tab _Storage_, then _Local Storage_ and finally right click `localhost` and _Delete All_.

**Comment by scarstreet** [comment]
Yes, I am using firefox and that did the trick! Thanks a lot!!
