### ISSUE TITLE
Use with encrypted localStorage

### ISSUE THREAD

**Issue by ttntm** [gabrielmbmb/vuex-multi-tab-state#9]
Hi, I'm wondering if there's any way to use this (really cool!) module together with encrypted localStorage (https://github.com/softvar/secure-ls).

I'm already using `secure-ls` for https://github.com/robinvdvleuten/vuex-persistedstate, so it'd be great if I could use the same (encrypted) localStorage for both modules.

I'd appreciate any ideas as to how this might be possible already; otherwise I'd like to submit this as a feature request.

**Comment by gabrielmbmb** [comment]
Hi @ttntm, at this moment the only compatible storage is the local storage. I will start to develop a way to give support to other storages like `secure-ls` or `js-cookie`. Thanks for using the plugin and I hope to have this feature soon.

**Comment by ttntm** [comment]
Thanks for considering it, maybe having a look at how it was implemented in `vuex-persistedstate` could help.

I'll use it as it is for now, which makes things so much easier already - thanks.
